name: HLint
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-setup@v2
        with:
          version: '3.8'
      - uses: haskell-actions/hlint-run@v2
        with:
          path: '["src/"]'
          fail-on: status
